const ACTIONS = {
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',
    SIGN_UP: 'SIGN_UP',
    SIGN_OUT: 'SIGN_OUT',

    USER_ROLE: 'USER_ROLE',

    ADD_EVENT: 'ADD_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT',
    DELETE_EVENT: 'DELETE_EVENT',

    ADD_POST: 'ADD_POST',
    UPDATE_POST: 'UPDATE_POST',
    DELETE_POST: 'DELETE_POST',

    DO_CONNECTION: 'DO_CONNECTION',
    UNDO_CONNECTION: 'UNDO_CONNECTION',

    RATING: 'RATING',
    UPDATE_RATING: 'UPDATE_RATING',

    GET_ALL_POSTS: 'GET_ALL_POSTS',
    GET_ALL_EVENTS: 'GET_ALL_EVENTS',
    GET_ALL_USERS: 'GET_ALL_USERS',

    JOIN_EVENT_ACTION: "JOIN_EVENT_ACTION",

    FILTER_POSTS: 'FILTER_POSTS',
    FILTER_EVENTS: 'FILTER_EVENTS',

    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    UPDATE_USER_VISITED_EVENTS: "UPDATE_USER_VISITED_EVENTS",

    GET_USER_SPECIFIC_EVENTS: 'GET_USER_SPECIFIC_EVENTS',
    GET_USER_SPECIFIC_POSTS: 'GET_USER_SPECIFIC_POSTS',

    ADD_NEW_COMMENT: "ADD_NEW_COMMENT",
    INCREASE_COMMENT_COUNT: "INCREASE_COMMENT_COUNT",
    GET_ALL_COMMENTS: "GET_ALL_COMMENTS",

    ADD_NEW_POST_COMMENT: "ADD_NEW_POST_COMMENT",
    INCREASE_POST_COMMENT_COUNT: "INCREASE_POST_COMMENT_COUNT",
    GET_ALL_POST_COMMENTS: "GET_ALL_POST_COMMENTS",

    TOGGLE_EVENT_LIKES: "TOGGLE_EVENT_LIKES",

    EVENT_SHARED: "EVENT_SHARED",

    UPDATE_USER_CONNECTIONS: "UPDATE_USER_CONNECTIONS",

    RATING_USER: "RATING_USER",

    UPDATE_HOME_EVENT_LIST: "UPDATE_HOME_EVENT_LIST",
    UPDATE_POST_LIST: "UPDATE_POST_LIST",

    TOGGLE_POST_LIKES: "TOGGLE_POST_LIKES",

    POST_SHARED: "POST_SHARED"
};
export default ACTIONS;